security:
  password_hashers:
    App\Entity\User:
      algorithm: auto
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      logout:
        path: dashboardLogout
        target: /
        invalidate_session: true
      custom_authenticators:
        - App\Security\DashboardAuthenticator

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/dashboard(?!/login|/logout|/samllogin|/samlvalidate), roles: ROLE_ADMIN }
