language: php
php:
  - 7.4
sudo: false
dist: bionic
addons:
  - mariadb: 10.5
install:
  - sudo mysql -e 'CREATE SCHEMA IF NOT EXISTS demo;'
  - sudo mysql -e 'USE mysql;'
  - sudo mysql -e 'CREATE USER "vagrant"@"localhost" IDENTIFIED BY "vagrant";'
  - sudo mysql -e 'GRANT ALL PRIVILEGES ON demo.* TO "vagrant"@"localhost";'
  - sudo mysql -e 'FLUSH PRIVILEGES;'
  - composer dump-autoload
  - composer i --no-scripts
  - php bin/console --no-interaction doctrine:migrations:migrate
  - php bin/console --no-interaction doctrine:fixtures:load
