services:
  signal_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker/logs/server:/var/log/nginx/
      - ./docker/logs/app:/var/www/html/var/log/
networks:
  default:
    external: true
    name: docker_default
