version: '3'
services:
  signal_app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./logs/server:/var/log/nginx/
      - ./logs/app:/var/www/html/var/log/
networks:
  default:
    external: true
    name: docker_default
